In [5]:
import pandas as pd

# Data tables for annual TEOTIL report

John Rune needs data tables for the 2016 TEOTIL report (see e-mail received 30/10/2017 14.58). This e-mail tests whether this data can be extracted easily from the NOPE output.

We need accumulated values for each of the 247 main catchments.

In [6]:
# Read data
in_csv = (r'C:\Data\James_Work\Staff\Oeyvind_K\Elveovervakingsprogrammet'
          r'\NOPE\nope_results_2015.csv')
df = pd.read_csv(in_csv)

df.head()

,regine,regine_ned,accum_all_point_tot-n_tonnes,accum_all_point_tot-p_tonnes,accum_all_sources_tot-n_tonnes,accum_all_sources_tot-p_tonnes,accum_anth_diff_tot-n_tonnes,accum_anth_diff_tot-p_tonnes,accum_aqu_tot-n_tonnes,accum_aqu_tot-p_tonnes,...,local_nat_diff_tot-n_tonnes,local_nat_diff_tot-p_tonnes,local_q_reg_m3/s,local_ren_tot-n_tonnes,local_ren_tot-p_tonnes,local_runoff_mm/yr,local_spr_tot-n_tonnes,local_spr_tot-p_tonnes,local_trans_tot-n,local_trans_tot-p
0,001.222Z,001.2220,0.119378,0.009030,2.474535,0.083063,0.909652,0.056942,0.0,0.0,...,1.445505,0.017092,0.085473,0.0,0.0,434.054654,0.108315,0.008135,1.00,1.00
1,002.DGBZ,002.DGB0,0.000000,0.000000,6.429953,0.137348,0.000000,0.000000,0.0,0.0,...,6.628817,0.165480,0.989583,0.0,0.0,362.624732,0.000000,0.000000,0.97,0.83
2,123.A1Z,123.A12,0.489527,0.023622,16.176846,0.308573,11.190604,0.246177,0.0,0.0,...,5.551500,0.129247,0.636149,0.0,0.0,503.427803,0.450727,0.065091,0.81,0.30
3,212.FAC,212.FAB0,0.021639,0.000779,6.659930,0.068712,0.000000,0.000000,0.0,0.0,...,6.987675,0.089385,0.495119,0.0,0.0,287.234419,0.022777,0.001025,0.95,0.76
4,135.1AC,135.1AB,0.000000,0.000000,5.817805,0.060086,0.000000,0.000000,0.0,0.0,...,6.844476,0.143063,1.092563,0.0,0.0,2452.318429,0.000000,0.000000,0.85,0.42

In [7]:
# Get data for just 247 main catchments
reg_ids = ['%03d.' % i for i in range(1, 248)]
df = df[df['regine'].isin(reg_ids)]
print len(df)

df.head()

247

,regine,regine_ned,accum_all_point_tot-n_tonnes,accum_all_point_tot-p_tonnes,accum_all_sources_tot-n_tonnes,accum_all_sources_tot-p_tonnes,accum_anth_diff_tot-n_tonnes,accum_anth_diff_tot-p_tonnes,accum_aqu_tot-n_tonnes,accum_aqu_tot-p_tonnes,...,local_nat_diff_tot-n_tonnes,local_nat_diff_tot-p_tonnes,local_q_reg_m3/s,local_ren_tot-n_tonnes,local_ren_tot-p_tonnes,local_runoff_mm/yr,local_spr_tot-n_tonnes,local_spr_tot-p_tonnes,local_trans_tot-n,local_trans_tot-p
1433,090.,24_90,26.419497,3.755995,107.457321,5.812710,45.604549,1.667594,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
2741,214.,210_247,177.394460,30.618483,193.704865,30.959414,0.000000,0.000000,176.861582,30.538551,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3009,066.,24_90,775.991566,131.469254,899.678189,135.535523,89.791458,3.632356,743.471422,127.323753,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4340,147.,136_160,124.227130,21.388063,140.438808,22.337333,10.759856,0.827354,116.931721,20.658404,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4986,201.,161_209,0.000000,0.000000,9.594404,0.217097,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [8]:
# Save output
out_csv = (r'C:\Data\James_Work\Staff\Oeyvind_K\Elveovervakingsprogrammet'
           r'\NOPE\nope_results_2015_main_catchments_only.csv')
df.to_csv(out_csv)